#trigger:
#  branches:
#    include:
#      - dev

variables:
  # This group has variables needed for the service principal to authenticate with Azure
  - group: azure-devops-service-principal
  - group: xledger-syncronizer-dev
  - name: azureSubscription
    value: 'c970b736-a87d-42e2-b2a6-73d193d9034e'
  - name: functionAppName
    value: 'xledger-syncronizer-dev'
  - name: functionAppRootDirectory
    value: '.'
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: infrastructureRootFolder
    value: 'infrastructure/dev'
  - name: tfvarsFile
    value: 'terraform.tfvars'
  - name: deploymentEnvironment
    value: 'env01'

stages:
# Deploy infrastructure with terraform.
- template: templates/deploy_infrastructure.yml
  parameters:
    infrastructureRootFolder: '$(infrastructureRootFolder)'
    tfvarsFile: '$(tfvarsFile)'
    deploymentEnvironment: '$(deploymentEnvironment)'
    vmImageName: '$(vmImageName)'

# Build and deploy function app.
- template: templates/build_and_deploy_function_app.yml
  parameters:
    azureSubscription: '$(azureSubscription)'
    functionAppName: '$(functionAppName)'
    vmImageName: '$(vmImageName)'
    functionAppRootDirectory: '$(functionAppRootDirectory)'
