trigger:
- main

variables:
  azureSubscription: 'c970b736-a87d-42e2-b2a6-73d193d9034e'
  vmImageName: 'ubuntu-latest'
  terraformWorkingDirectory: '$(Build.SourcesDirectory)/infrastructure/terraform'
  terraformVersion: '1.8.5'
  environment: 'dev'  # Set this to 'prod' for production environment

stages:
- stage: Infra
  displayName: 'Infrastructure Deployment'
  jobs:
  - job: DeployInfra
    displayName: 'Deploy Infrastructure'
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          curl -LO "https://releases.hashicorp.com/terraform/${terraformVersion}/terraform_${terraformVersion}_linux_amd64.zip"
          unzip terraform_${terraformVersion}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version
      displayName: 'Install Terraform'

    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd $(terraformWorkingDirectory)
          if [ "$(environment)" = "dev" ]; then
            cp backend-dev.tf backend.tf
          else
            cp backend-prod.tf backend.tf
          fi
          terraform init
      displayName: 'Terraform Init'

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd $(terraformWorkingDirectory)
          terraform plan -var-file="$(environment).tfvars"
      displayName: 'Terraform Plan'

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd $(terraformWorkingDirectory)
          terraform apply -var-file="$(environment).tfvars" -auto-approve
      displayName: 'Terraform Apply'

#- stage: Build
#  displayName: 'Build Stage'
#  dependsOn: Infra
#  condition: succeeded()
#
#  jobs:
#  - job: Build
#    displayName: 'Build'
#    pool:
#      vmImage: $(vmImageName)
#
#    steps:
#    - task: UsePythonVersion@0
#      displayName: 'Use Python 3.11'
#      inputs:
#        versionSpec: 3.11
#
#    - bash: |
#        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
#      workingDirectory: $(workingDirectory)
#      displayName: 'Install application dependencies'
#
#    - task: ArchiveFiles@2
#      displayName: 'Archive files'
#      inputs:
#        rootFolderOrFile: '$(workingDirectory)'
#        includeRootFolder: false
#        archiveType: zip
#        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#        replaceExistingArchive: true
#
#    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#      artifact: drop
#
#- stage: Deploy
#  displayName: 'Deploy Stage'
#  dependsOn: Build
#  condition: succeeded()
#
#  jobs:
#  - deployment: Deploy
#    displayName: 'Deploy'
#    environment: 'development'
#    pool:
#      vmImage: $(vmImageName)
#
#    strategy:
#      runOnce:
#        deploy:
#          steps:
#          - task: AzureFunctionApp@2
#            displayName: 'Deploy Azure Function App'
#            inputs:
#              azureSubscription: '$(azureSubscription)'
#              appType: functionAppLinux
#              appName: $(functionAppName)
#              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
