parameters:
- name: infrastructureRootFolder
  type: string
- name: tfvarsFile
  type: string
- name: deploymentEnvironment
  type: string
- name: vmImageName
  type: string

stages:
- stage: 'Terraform_Plan'
  displayName: 'Terraform Plan'
  jobs:
  - job: 'Terraform_Plan_Job'
    displayName: 'Terraform Plan'
    pool:
      vmImage: ${{ parameters.vmImageName }}

    steps:
    - script: |
        echo "Running Terraform init..."
        terraform init
        echo "Running Terraform plan..."
        terraform plan \
          -var-file ${{ parameters.tfvarsFile }} \
          -out=$(Build.ArtifactStagingDirectory)/tfplan.binary \
          -var "api_key=$(api_key)" \
          -var "cost_categories_flex_link=$(cost_categories_flex_link)" \
          -var "employee_groups_flex_link=$(employee_groups_flex_link)" \
          -var "employment_types_flex_link=$(employment_types_flex_link)" \
          -var "project_groups_flex_link=$(project_groups_flex_link)" \
          -var "generator_report_flex_link=$(generator_report_flex_link)"
      displayName: 'Terraform Plan'
      workingDirectory: ${{ parameters.infrastructureRootFolder }}
      env:
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

    - publish: $(Build.ArtifactStagingDirectory)/tfplan.binary
      artifact: terraformPlanArtifact
      displayName: 'Publish Terraform Plan'

- stage: 'Terraform_Apply'
  displayName: 'Terraform Apply'
  dependsOn: 'Terraform_Plan'
  condition: succeeded()
  jobs:
  - deployment: 'Terraform_Apply_Job'
    displayName: 'Terraform Apply'
    pool:
      vmImage: ${{ parameters.vmImageName }}
    environment: ${{ parameters.deploymentEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - download: current
            artifact: terraformPlanArtifact
            displayName: 'Download Terraform Plan'

          - script: |
              echo "Running Terraform init..."
              terraform init
              echo "Running Terraform apply using the saved plan..."
              terraform apply -auto-approve "$(Pipeline.Workspace)/terraformPlanArtifact/tfplan.binary"
            displayName: 'Terraform Apply'
            workingDirectory: ${{ parameters.infrastructureRootFolder }}
            env:
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
